### ISSUE TITLE
Using the App?

### ISSUE THREAD

**Issue by gaetgu** [samuelcarreira/dynamic-time-shifting-desktop#2]
Ok, so first of all thanks so much for creating what I have been waiting for since MacOS first came out with the feature. I assume. I downloaded the app, opened it, made sure it was what I wanted, set it to be a start-up application, then restarted my computer. Nothing. I checked and made sure that it was in start-up apps, restarted again. Again, nothing. I am not quite sure how to actually run it. I can run the preview. Am I just supposed to open the preview and do something with that? If you could update the README to include those kind of instructions it would be great. 

I am using Elementary OS 5.1 Hera and GTK 3. 

Any help is greatly appreciated as I have been (like I said earlier) looking for months.

**Comment by samuelcarreira** [comment]
Hi there, thank you for proving the details. This simple app uses the auto launch node module ( https://github.com/Teamwork/node-auto-launch ) to add a startup entry.
Maybe there is a some incompatibility with your OS. My advice is to manually to add the app to the system startup, maybe this link helps: https://elementaryos.stackexchange.com/questions/350/how-to-edit-startup-applications

Also, if the app doesn’t change the wallpaper automatically (the preview as the name says it’s only a preview window), you have another incompatibility with the current OS. I’ve only tested with a more common Linux distribution (Ubuntu) so I cannot provide more support for other distros.

Kind regards

**Comment by gaetgu** [comment]
Hello, I am sorry to bug you, but after about twenty kernel panics and two new hard drives ruined, I am back on Ubuntu from EOS. I have installed your app and the auto-launch feature, and the app is in system startup. When I start up the computer, I just get my default background. I can start up the app and preview it, but it won't actually display on the desktop. Any help is appreciated, Thanks again for making such an awesome app!

**Comment by gaetgu** [comment]
@samuelcarreira

**Comment by samuelcarreira** [comment]
@gaetgu, thank you for your continuous interest in this app, but at present, I can't help you because I will not support anymore this app.
But I am glad to announce in the first hand that I am planning to develop a version 2.0 of this app. I cannot promise a release date because I need to finish other open-source projects first, but I can describe some of the features of the 2.0 versions:

- Update used libraries (maybe the new wallpaper changing library will fix your particular issue)
- Control the app functionality on the main process. I know that is not the best practice, but with this change, I will only need the renderer process to show the app settings/control so the app will consume less RAM while is running in the background (minimized to the tray)
- Rewrite code in typescript 
- Automatic updates (maybe)
- Other user suggestions...

Kind regards
